version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: yellow-first-pg
    environment:
      POSTGRES_DB: yellowfirst
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    networks:
      - pg-network
    volumes:
      - pg-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pg-admin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - '5050:80'
    networks:
      - pg-network

networks:
  pg-network:

volumes:
  pg-data:
